#!/bin/bash

volume() {
  mute=`pactl list sinks | grep "Mute: " | cut -d: -f 2 | tr -d [:blank:]`
  [[ $mute == 'no' ]] && echo  `pactl list sinks | grep "Volume: f" | cut -d'/' -f2 | tr -d [:blank:]` && return
  [[ $mute == 'yes' ]] && echo ' 0%' && echo && echo '#458588'
}

case $BLOCK_BUTTON in
  1) pavucontrol ;;
  3) pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo toggle ;;
  4) pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +1% ;;
  5) pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -1% ;;
esac

volume
